### ISSUE TITLE
Not Converting to MEFL

### ISSUE THREAD

**Issue by kkiwimagi** [cytoflow/cytoflow#259]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do? Trying to convert data to MEFL
  - What happened? It is return unconvered raw vales
  - What did you expect to happen? As this is a fresh install cytoflow I expected to have converted to MEFL
  
**Don't forget to attach the log file to this bug report!**  not sure how to create a log file

**Comment by kkiwimagi** [comment]
Hi Brain,

I traced the problem down to my addition of the AJ01 beads. I thought I only needed to put the values in a dictionary but it looks like that is in sufficient. I am about to go through your code line by line to try and find the issue. Ross Matlab code seams to be working fine for this data set with the AJ01 beads; however, as I have invested a good deal of effort for using cytoflow I would really like to solve this issue. Any assistance would be greatly appreciated.

Also do you know if changing the beads has plans for become a user can input directly as changing the source code it quite troublesome?

Thank you for your time,
Katherine

**Comment by bpteague** [comment]
Hi Kathrine - sorry it's been over a year since you filed this report! You're using the Python modules, yes? You don't need to change the source code to use new beads. Rather, the `beads` attribute of the `BeadCalibrationOp` class takes a dictionary -- the keys are the units (like MEFL or MEPTR), and the values are lists of the bead intensities (from the Spherotech calibration sheets.)

The `BeadCalibrationOp.BEADS` dictionary is just a place where I put a bunch of those values to make them easy to use.

I will note that, as of today, I've updated that dictionary with all of the latest data from Spherotech. I should have a new version released in the next couple of weeks.

And if you're using the GUI, you're pretty much stuck with the values that are in the code!

If you're still having trouble, feel free to re-open the ticket (or email me directly (; )
