### ISSUE TITLE
Normalization of diluted values

### ISSUE THREAD

**Issue by flip1311** [cytoflow/cytoflow#261]
Hello everyone,

because of the reason I have a big range of particle density in my measurements I diluted the samples depending on the amount of particles. 

Now my question is how could I normalize the values depending on the dilution so that I could use cytoflow to compare different groups of samples? 

Thanks in advance

**Comment by bpteague** [comment]
Here's the conversation we had over email:
Ah, the Accuri C6 is a volumetric instrument. So yes, in theory you could use it to measure raw counts. However, just because you *can* doesn't mean you *should.*

Here's an example.  I have a tube of cells, 10% of them are GFP-positive and 90% of them are GFP-negative. It has a concentration of 1000 cells/µl. My instrument manager says that's too many cells, so I dilute it 1:2 -- now the diluted tube has 500 cells per µl.  However, in the diluted tube, 10% are still GFP-positive and 90% are still GFP-negative. Even if the concentration changes, the proportion doesn't.

I suppose you could say "I analyzed 20 ul of the sample. There were a total of 10,000 events, so the concentration was 500 cells/µl. 9,000 of them were GFP-negative and 1,000 were GFP-positive. However, that was a sample diluted 1:2, so the original tube has 1000 cells/µl, and if I had analyzed that directly I would have measured 18,000 GFP-negative cells and 2,000 GFP-positive cells." But that still doesn't give you any more information over the original cell concentration and the proportion in each gate.

In any case, if you want to report the "original" tube concentration, there's really nothing in the point-and-click Cytoflow interface that will help you. If you're using a Jupyter notebook, you could use the TransformStatisticOp operation to multiply each tube's statistics by its dilution factor.

I'm sorry if this isn't quite as helpful as you were hoping for!

Best,
Brian

PS - I'm impressed that you're running the BD Accuri software on Wine! Is that a Fedora desktop? (I'm an Ubuntu person myself...) Are you actually controlling the instrument, or just doing data analysis?
