### ISSUE TITLE
Question about using with non FCS data

### ISSUE THREAD

**Issue by henrypinkard** [cytoflow/cytoflow#264]
Hi I'm hoping I might be able to use this package with some flow cytometry-like data that does not actually come from a flow cytometer. Essentially, I have a bunch of multi-channel datapoints and I'd like to use this package to analyze them, but I have the data in it's raw format (i.e. a big numpy array). I'm wondering if you think it is possible to manually create a dataset from this, and still make use of all the downstream features for visualization and analysis?

**Comment by bpteague** [comment]
Hi @henrypinkard -- you're not the first person to ask. I'm glad you think there's some useful functionality here -- but quite a few portions of the package assume that the data is from a flow cytometer.  This is quite explicitly baked into the point-and-click GUI; less so with the Python modules.

If you want to give it a go (and are using the Python modules), have a look at the `Experiment` module. You'll have to build one of those manually -- instead of creating one with `ImportOp` -- and you'll obviously need to avoid modules that explicitly expect other FCS files to parameterize them.  But otherwise, once you've got a fully-formed `Experiment`, you should be fine to use (most of) the rest of the package? Let me know how you get on.

**Comment by henrypinkard** [comment]
Thanks for the response @bpteague. This was a mission-critical part of my research, so I ended up developing something from scratch in python
