### ISSUE TITLE
Saving workflow --> Error/ 0 Bytes

### ISSUE THREAD

**Issue by NessaNoctiluca** [cytoflow/cytoflow#275]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do? Trying to save the current/ just set up workflow
  - What happened? Error message or a file with 0 Bytes was saved
  - What did you expect to happen? Save the file
  
**Don't forget to attach the log file to this bug report!** 
[SavingError_200828.log](https://github.com/bpteague/cytoflow/files/5141845/SavingError_200828.log)

**Comment by bpteague** [comment]
@NessaNoctiluca - thanks for the bug report, and thanks in particular for uploading the log! (And sorry for the delay in getting to it.) This was the result of a change in the `pandas` API, which should be fixed in the next release. I'll be finishing it and uploading it in the next few weeks. If you are still having an issue, please re-open the bug.
