### ISSUE TITLE
Logicle Scale Factory example for Matplotlib 

### ISSUE THREAD

**Issue by crife-pact** [cytoflow/cytoflow#297]
### DESCRIPTION:
  - What were you trying to do? Gain more control over generating scatterplots. Specifically, I need more options for controlling the coloring associated with the samples. Huefacet is not sufficient.
  - What happened? Tried to use the logicle scale with plt.scatterplot and each attempt failed with various error messages
    - matplotlib.scale.register_scale(cytoflow.utility.logicle_scale.MatplotlibLogicleScale)
    - matplotlib.scale.register_scale(util.scale_factory('logicle', ex, channel))
    - other variations
  - What did you expect to happen? Plot a scatterplot with colors of my choosing. I see the note at [https://github.com/cytoflow/cytoflow/blob/master/cytoflow/utility/logicle_scale.py#L363](https://github.com/cytoflow/cytoflow/blob/master/cytoflow/utility/logicle_scale.py#L363) but don't understand the solution. 
  
```
/opt/miniconda3/envs/cytoflow/lib/python3.6/site-packages/cytoflow/utility/logicle_scale.py in get_transform(self)
    361             # from utility.scale.scale_factory().
    362 
--> 363             raise CytoflowError("You can't set a 'logicle' scale directly.")
    364 
    365         return MatplotlibLogicleScale.LogicleTransform(logicle = self.logicle)

CytoflowError: You can't set a 'logicle' scale directly.
```

**Comment by crife-pact** [comment]
I figured it out...

```
import cytoflow.utility.logicle_scale
import cytoflow.utility as util

# generate the scales for matplotlib
logicle_x = util.scale_factory('logicle', ex, channel='X')
logicle_y = util.scale_factory('logicle', ex, channel='Y')

# set logicle scale
plt.gca().set_xscale('logicle', **logicle_x.get_mpl_params(g.axes.get_xaxis()))
plt.gca().set_yscale('logicle', **logicle_y.get_mpl_params(g.axes.get_yaxis()))
```

**Comment by bpteague** [comment]
Do note that in a2828a9ac611ba501755879c51c4e45ed94e4d19 I added a `palette` argument to the views' `plot()` function, which lets you change the colors of the plot (:

Also note that the logicle scale isn't really intended to be used stand-alone, primarily because it is *parameterized* -- you have to give it an experiment and a channel (or a statistic), and it derives the scale's parameters from that channel. If you're only planning to plot that data, you will probably be fine -- but if you plot something else, you'll get unexpected results!
