### ISSUE TITLE
Inconsistent behaviour across Gates

### ISSUE THREAD

**Issue by AlFontal** [cytoflow/cytoflow#326]
I've been using the `cytoflow` library to perform some manual gating in CyTOF experiments. 
However, I have discovered an unexpected inconsistent behaviour between gates defined with the `Range2DOp` and the `PolygonOp` operations. While the former defines a gate with inclusive borders, the latter defines gates with exclusive borders. 

This gave me some clunky/unexpected results when setting certain boundaries at 0.

Looking at the definition of both operations, one can see where the inconsistencies come from:

+ The `Range2DOp` checks for inclusion of each point within the boundaries using the `pandas.Series.between()` method, which, by default, uses _inclusive_ boundaries.

+ The `PolygonOp` checks for inclusion by using the `matplotlib.path.Path.contains_points()` method, which, by default, uses _exclusive_ boundaries. 

As a matter of fact, in the [matplotlib path API documentation](https://matplotlib.org/stable/api/path_api.html), they mention that:

> The current algorithm has some limitations:
   The result is undefined for points exactly at the boundary (i.e. at the path shifted by radius/2).
   ...

I would, in fact, like the default behaviour to be inclusive, but this doesn't seem to be possible to be done using the `Path.contains_points()` method. The pandas `between` method accepts a parameter to make the boundaries exclusive, but I am also guessing this would be a rather breaking change.

I will think of a solution that doesn't make the `contains_points` operation much more expensive, but just wanted to raise this issue at the moment.

**Comment by kristjaneerik** [comment]
There's quite a bit of discussion here https://stackoverflow.com/questions/36399381/whats-the-fastest-way-of-checking-if-a-point-is-inside-a-polygon-in-python

**Comment by bpteague** [comment]
@kristjaneerik -  thanks for the pointer to that StackOverflow thread. I probably found it when I originally wrote the function back in 2016 or so. The `numba` stuff wasn't there, that's for sure.

@AlFontal - I can see the value in keeping these operations consistent. I was going to say that I can't see any *a priori* reason for these gates being inclusive or exclusive -- are points that fall directly on a threshold above or below? But if you're working CyTOF data, or data that has been converted to absolute units (bead calibration), then events that land directly on 0 should be included by a threshold at 0.

(And honestly, any workflow that breaks because a threshold has gone from inclusive to exclusive was broken already.)

`cytoflow` depends on so much of the scientific python ecosystem -- I guess we can add `numba` to that list, too. Let me hack something together.

**Comment by bpteague** [comment]
(note: the `numba` dependency adds another 25 Mb to the download size. but if it's already half a gig.... :/ )

**Comment by bpteague** [comment]
Fixed by b9ef62f81c8b596f5acc499e6e2b5161cfadaa1a -- thanks for the report.
